### ISSUE TITLE
TODO-List for GSoC 2020

### ISSUE THREAD

**Issue by siko1056** [Abdallah-Elshamy/octave#12]
- [x] Document escape characters with double and single quoted strings. See [cset 174550af014f](https://hg.savannah.gnu.org/hgweb/octave/rev/174550af014f).
- [x] Add docstrings to interpreter manual, with small text. See [34696240591e](https://hg.savannah.gnu.org/hgweb/octave/rev/34696240591e).
- [x] <strike>Move `equals` to `string_vector` class.</strike>  See [cset 173807014259](https://hg.savannah.gnu.org/hgweb/octave/rev/173807014259).
- [x] Check includes `configure.ac`.

**Comment by Abdallah-Elshamy** [comment]
Hi,

I have some good news. I was able to disable the `PrettyWriter` option if an old version of `RapidJSON` exists here in 2236199.

If the old version exists. The code is still built successfully (I have tested this on my machine) and If the user tried to use the `PrettyWriter` option, Octave will raise the following warning:
```
warning: RapidJSON 1.1.0 or older found, but latest development version needed. Octave will not be able to support 'PrettyWriter' option in 'jsonencode'.
``` 
and return an ordinary output as if he called the function without the `PrettyWriter` option.

If you have any feedback. please let me know.

**Comment by siko1056** [comment]
Thank you for this change, but I suggest two additional changes.

1. `HAVE_NEW_RAPIDJSON` is not clever.  I you look for macros, you first would try `grep -R HAVE_RAPIDJSON` and you don't see the new macro.  Please consider using `HAVE_RAPIDJSON_NEW` or better `HAVE_RAPIDJSON_DEV` instead.

2. Unfolding the header lookup has a drawback `HAVE_RAPIDJSON 0` and `HAVE_RAPIDJSON_DEV 1` is possible and why checking for a header, if we cannot even find `rapidjson/rapidjson.h`?  I would prefer an interleaved branch.  Can you try

```
AC_LANG_PUSH([C++])
AC_CHECK_HEADER([rapidjson/rapidjson.h], [have_rapidjson=yes], [have_rapidjson=no
  rapid_json_warning="RapidJSON library not found.  Octave will not be able to read or write JSON files."])
if test "$have_rapidjson" = yes; then
  AC_CHECK_HEADER([rapidjson/cursorstreamwrapper.h], [have_rapidjson_dev=yes], [have_rapidjson_dev=no
    rapid_json_warning="RapidJSON 1.1.0 or older found, but latest development version needed. Octave will not support the \'PrettyWriter\' option in \'jsonencode\'."])
fi
if test "$have_rapidjson" = yes; then
  AC_DEFINE(HAVE_RAPIDJSON, 1, [Define to 1 if RapidJSON is available.])
  if test "$have_rapidjson_dev" = yes; then
    AC_DEFINE(HAVE_RAPIDJSON_DEV, 1, [Define to 1 if the development version of RapidJSON is available.])
  fi
else
  OCTAVE_CONFIGURE_WARNING([rapid_json_warning])
fi
AC_LANG_POP([C++])
```

**Comment by Abdallah-Elshamy** [comment]
Good suggestions. I amended the commit and here is the new one 8e4c55f.

**Comment by siko1056** [comment]
Thanks, I pushed a modified version to the development branch [aae9d7f098bd](https://hg.savannah.gnu.org/hgweb/octave/rev/aae9d7f098bd).

Now you can fully focus on your files and the manual.

About the "Move equals to string_vector class." issue I take care now.

**Comment by siko1056** [comment]
> About the "Move equals to string_vector class." issue I take care now.

Not necessary, see list in first post :smile: :tada:

**Comment by Abdallah-Elshamy** [comment]
That's a much simpler solution. Great job ! Now, half of the list is done.

For now I am focusing on the manual.

I think the best position for the docstrings is in `strings.txi`. I am thinking about righting a few sentences about JSON then inserting the docstrings. What do you think ?

Should I put all of this as a new `@section` in `@node String Conversions` or make a new `@node` some thing like `@node JSON encoding/decoding` ?

**Comment by siko1056** [comment]
You are right, I think a `@section` in the [string conversions section](https://octave.org/doc/v5.2.0/String-Conversions.html) looks suitable.

**Comment by siko1056** [comment]
Today I found some time or testing our project, please read

https://siko1056.github.io/blog/2020/08/19/gsoc2020-json-benchmark.html

Maybe it sounds a little pessimistic, but your work is undoubtedly great and maybe we have something to do for the time after GSoC :wink:   Let's discuss this tomorrow.

**Comment by Abdallah-Elshamy** [comment]
Hello,

While working on Documents and tests for escape characters, I noticed a minor issue. The issue is that `jsonencode` ignores anything after the null character `\0`. for example:
```
jsonencode("abc\0def")
--> ans = "abc"
```
in MATLAB:
```
jsonencode(sprintf("abc\0def"))
--> ans = "abc\u0000def"
```

I investigated this and found that the reason for it is due to calling `c_str()` in 
```
writer.String (char_vector.c_str ());
```
as `c_str()` terminates the string after `\0`. As a solution for this I tried replacing any `\0` with `\u0000`.
But I tried in external file the following:
```
writer.String ("\u0000abc");
```
and the output was 
```
---> ans = ""
```
So apparently RapidJSON detects `\u0000` and have the same effect as `c_str ()`

Do you have any ideas how to get this to be MATLAB-compatible?

If there isn't, I guess we have to choose from the following options (If you have other options, please let me know):
* Leave it as it is and add a note about it in the manual.
* Change only this character by replacing it with `\\u0000` and preserve other characters as they work correctly.
* Don't preserve escape characters at all and convert double-quoted strings to single-quoted strings.

I don't know what is the optimal option for Octave so I can't recommend any one. But, I think that the last one is not favorable as MATLAB supports this.

What do you think is the best option ?

**Comment by siko1056** [comment]
Hmm, this only happens for the double quoted string case.  Was it possible in this case to do the the escaping beforehand?

```
jsonencode("abc\\0def")
```

has the same result as in Matlab.

Something like [std::string::replace](https://en.cppreference.com/w/cpp/string/basic_string/replace) before calling `c_str()`?

https://hg.savannah.gnu.org/hgweb/octave/file/f0414ee0fefe/libinterp/corefcn/jsonencode.cc#l113

**Comment by Abdallah-Elshamy** [comment]
Hi,

I have some good news this time :smile: :tada: :tada:

Since the performance of `jsondecode` was bad in decoding large files, I was trying to identify some bottlenecks that we may improve during the rest of GSoC.

Performing better in decoding numeric JSON data was strange for me. Specially the gigantic difference in performance between numeric JSON data and mixed JSON data.

The mixed data was mostly JSON objects, so I checked for bottlenecks in the path that decoding object takes.

The reason for such a bad performance seems to be the calling of `makeValidName` function from the interpreter (This totally went over my head :sweat_smile:).

To verify this I removed the code that calls it:
https://hg.savannah.gnu.org/hgweb/octave/file/f0414ee0fefe/libinterp/corefcn/jsondecode.cc#l101

Then, I recompiled the code and used your benchmark to assess the performance.
https://siko1056.github.io/blog/2020/08/19/gsoc2020-json-benchmark.html

This is the performance without `makeValidName`: (Note: octave-rapidjson doesn't also use `makeValidName`.)

![comparison](https://user-images.githubusercontent.com/33662044/91178064-e9f06800-e6e4-11ea-8ad6-9b3c2816eea9.png)

I didn't use the supplied metrics for MATLAB as it was on a different machine.
So, the problem seems to be the calling of `makeValidName`.

Also while searching for methods to improve the performance, I found that RapidJSON supports "In situ" decoding. See more about it here:
https://rapidjson.org/md_doc_dom.html#InSituParsing

I tried it and assessed it using the benchmark and this is the results:

![comparison_in_situ](https://user-images.githubusercontent.com/33662044/91183631-fe842e80-e6eb-11ea-9f00-73a44705dfb3.png)

The time performance didn't improve that much but the memory usage should be better. Should we use this method ?

**Comment by Abdallah-Elshamy** [comment]
> Hmm, this only happens for the double quoted string case. Was it possible in this case to do the the escaping beforehand?
> 
> ```
> jsonencode("abc\\0def")
> ```
> 
> has the same result as in Matlab.

In MATLAB, to preserve the escape characters, you must use `sprintf`. In Octave, we use double quotes to preserve them.
In MATLAB for example:
```
jsonencode("abc\0def")
--> ans--> "abc\\0def"
```
but if we use sprintf we will get this:
```
jsonencode(sprintf("abc\0def"))
--> ans--> "abc\u0000def"
```
But in the current version of `jsonencode`
```
jsonencode('abc\0def')
--> ans--> "abc\\0def"
```
but if we use the double quotes that should preserve the character
```
jsonencode(sprintf("abc\0def"))
--> ans--> "abc"
```

> Something like [std::string::replace](https://en.cppreference.com/w/cpp/string/basic_string/replace) before calling `c_str()`?
> 
> https://hg.savannah.gnu.org/hgweb/octave/file/f0414ee0fefe/libinterp/corefcn/jsonencode.cc#l113

I was able to do this but with a different method. But, by this we will preserve this character and escape the others.

To be MATLAB compatible when using double quotes (escaping when using double quotes), we will sacrifice the feature of preserving the characters.

**Comment by siko1056** [comment]
Thanks for the detailed answers.  Where can I find your code changes for jsondecode? :innocent: I care about the Octave git mirror to be more up-to-date with @mtmiller's help.

In any way we should talk tomorrow about this.  I think I don't get the escape problem right :sweat:

**Comment by Abdallah-Elshamy** [comment]
> Thanks for the detailed answers. Where can I find your code changes for jsondecode? innocent I care about the Octave git mirror to be more up-to-date with @mtmiller's help.
> 

Sorry for not providing links for them. Here is the changes to disable calling 'makeValidName' function:
https://gist.github.com/Abdallah-Elshamy/fad132332d5162e66d72dd3fc6d27082

Here is the changes to use 'In-situ' parsing
https://gist.github.com/Abdallah-Elshamy/44c0fcb8f0259fd6c62001ebb06d70ee

We should decide tomorrow what can we do to improve this.

**Comment by siko1056** [comment]
Thanks, now I made the experiments myself and can confirm your observations:
- `makeValidName` is the guilty one :tada:  To overcome this, I suggest to not make your valuable code dirty, but to provide a C++ implementation of makeValidName, that the m-file calls something like `__makeValidName__.cc` internally.
- For 'In-situ' parsing:  The performance gain was not overwhelming (just a few milliseconds maybe).  Is it available for RapidJSON 1.1.0?  If yes we can go for it.

**Comment by Abdallah-Elshamy** [comment]
Hello,

This [gist](https://gist.github.com/Abdallah-Elshamy/0262c5db4c7c49141d4d6ea881e837f8) contains the changes to document and test for escape characters.

**Comment by siko1056** [comment]
Thanks for all the clarifications.  Now GSoC is officially done for you :tada: :slightly_smiling_face:   Thank you for your contributions for Octave and please stay with us, there is always something to improve :wink:
